version: '3.8'
services:
  # nginx:
  #   image: nginx
  #   depends_on:
  #     - api
  #     # - frontend
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3050:80"

  api:
    container_name: api
    build:
      context: ./BackendApi
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:5000"
    ports:
      - 5000:5000

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - api
  #     - sqlserver